apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users # select the users pod and expose
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users # label by which pod can be selected
    spec:
      containers:
        - name: users-api
          # image: sailesh94/users-api:latest  
          image:  gomurali/k8s-users:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: "mongodb://admin:admin-password@mongodb-service:27017/?authSource=admin"
            - name: AUTH_API_ADDRESSS
              value: "auth-service.default:3000"

---
# MongoDB StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin-password
---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
