apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users # select the users pod and expose
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users # label by which pod can be selected
    spec:
      containers:
        - name: users-api
          image: sailesh94/users-api:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: "mongodb+srv://sailesh:<password>@cluster0.3wbp5dt.mongodb.net/"
            - name: AUTH_API_ADDRESSS
              value: "auth-service.default:3000"
