apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users # select the users pod and expose
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users # label by which pod can be selected
    spec:
      containers:
        - name: users-api
          # image: sailesh94/users-api:latest  
          image:  gomurali/k8s-users:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: "mongodb://sailesh:<>@docdb-2024-01-16-04-31-09.cluster-c5qsmk6aicub.us-east-1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
            - name: AUTH_API_ADDRESSS
              value: "auth-service.default:3000"
